version: "3.2"
services:
  react:
    image: react-dev
    volumes:
      - type: bind
        source: ../
        target: /code
      - type: bind
        source: ./node_modules
        target: /code/node_modules
    build:
      context: ../
      dockerfile: docker/react/Dockerfile-dev
    ports:
      - "1337:1337"
      - "7331:7331"
    environment:
      - HOST=localhost
      - REACT_NPM_INSTALL=on
  django:
    image: django-dev
    volumes:
      - type: bind
        source: ./venv
        target: /venv
      - type: bind
        source: ../djangoapi
        target: /code
    build:
      context: ../
      dockerfile: docker/django/Dockerfile-dev
    ports:
      - "8000:8000"
    environment:
      - DJANGO_PIP_INSTALL=on
      - DJANGO_MANAGEPY_MIGRATE=on
      - DJANGO_MANAGEPY_COLLECTSTATIC=xon 