FROM django-base

RUN mv /venv.tmp /venv

COPY docker/django/docker-entrypoint.sh /docker-entrypoint.sh

COPY djangoapi /code

ENV PYTHONPATH=/code/ UWSGI_VIRTUALENV=/venv UWSGI_WSGI_FILE=/code/djangoapi/wsgi.py UWSGI_SOCKET=:8000 UWSGI_MASTER=1 UWSGI_WORKERS=2  UWSGI_THREADS=8 UWSGI_UID=1000 UWSGI_GID=2000 UWSGI_LAZY_APPS=1 UWSGI_WSGI_ENV_BEHAVIOR=holy

CMD ["/venv/bin/uwsgi", "--http-auto-chunked", "--http-keepalive"]

EXPOSE 8000

ENTRYPOINT ["/docker-entrypoint.sh"]
